### PR TITLE
lodash use cherry-pick methods for smaller browserify/rollup/webpack bundles

### PR DESCRIPTION
**Pull request by aben**

### CODE REVIEW

**Comment by svnm** [comment]
Hey @Aben thanks for all your help on this, I will make you a Collaborator for this repo so you can test and merge in if all is working well. I can give you access to publish it on npm as well, I forget how to do this though, give me some time to find the documentation.

**Comment by aben** [comment]
Thanks, I will do my best.

**Comment by aben** [comment]
@StevenIseki 

``` sh
#Add a new user as a maintainer of a package
npm owner add <user> <package name>
```

https://docs.npmjs.com/cli/owner

**Comment by svnm** [comment]
Thanks no problem, what is you npm user name?

**Comment by aben** [comment]
`tntaben`

**Comment by svnm** [comment]
should be all good now 👍

**Comment by aben** [comment]
yeah, I have been published 2.0.1

**Comment by svnm** [comment]
you can publish it no problem: `npm version patch` then `npm publish` Looks to be working for me.

**Pull request merged**
